### ISSUE TITLE
meeting notes 2015-11-24

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/oncokb#39]
- [ ] filter by recruiting status
 - [ ] add cancer type in the summary
 - [ ] provide a table view?
 - [ ] editing a predicted biomarker does not remove the predicted biomarker
 - [ ] enable gene alias

**Comment by zhx828** [comment]
@jjgao I moved this list to ctmole repositor https://github.com/cBioPortal/ctmole/issues/14
